const dfis = [
'Banco de Inversion y Comercio Exterior',
'Brazilian Development Bank',
'PPP Canada',
'Business Development Bank of Canada',
'China Development Bank',
'China Silk Road Fund',
'Agence Française de Développement',
'Caisse des Depots et Consignations',
'Proparco',
'BPIFrance Investissement and BPIFrance Financement',
'KfW Group',
'KfW Development Bank',
'KfW IPEX-Bank',
'German Investment & Development Corporation',
'Power Finance Corporation',
'Infrastructure Development Finance Company',
'India Infrastructure Finance Company',
'Indian Renewable Energy Development Agency',
'Sarana Multi Infrastruktur',
'Indonesia Infrastructure Guarantee Fund',
'Cassa depositi e prestiti',
'Japan International Cooperation Agency',
'Japan Oil Gas and Metals National Corporation',
'Development Bank of Japan',
'Korea Development Bank',
'Korea Finance Corporation',
'Korea International Cooperation Agency',
'Nacional Financiera',
'VEB-RF',
'Public Investment Fund',
'Saudi Fund for Development',
'Saudi Industrial Development Fund',
'Development Bank of Southern Africa',
'Industrial Development Corporation of South Africa',
'Development Bank of Turkey',
'CDC Group Plc',
'Department for International Development',
'U.S. International Development Finance Corporation',
]

export default dfis
